<style>
form.elegante input {
padding: inherit;
}
form fieldset {
float: left;
width: 99%;
height: 400px;
color:  blue;
background-image: url(../Imagenes/tablita5.png);
 background-repeat: no-repeat;
}
form legend{
    color:red;
    font-family:  cursive;
    font-size:large;

}
</style>
<center>
<form>
<fieldset>
<legend>...</legend>
<div>
<?php
echo $this->form;
?>
</div>
</fieldset>
</form>
    </center>